apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  project: cicd-poc
  source:
    repoURL: git@github.com:hrushikeshkothem/cicd-poc.git
    targetRevision: main
    path: argocd/clusters
    directory:
      recurse: true
      jsonnet: {}
      exclude: '{**/apps/**,**/argo-apps/**}'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
