apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: nginx-test
  labels:
    app: test-app
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 80
  selector:
    app: test-app
